[en]
  languageName = "English"
  weight = 1
  contentDir = "content/en"

 [zh-cn]
  languageName = "简体中文"
  weight = 2
  contentDir = "content/zh-cn"

 [zh-tw]
  languageName = "繁體中文"
  weight = 3
  contentDir = "content/zh-tw"

 [fr]
  languageName = "Français"
  weight = 5
  contentDir = "content/fr"

[es]
  languageName = "Español"
  weight = 6
  contentDir = "content/es"

