[[main]]
  name = "Servicios"
  identifier = "servicios"
  # pre = '<i class="fas fa-fw fa-chevron-circle-down"></i>'
[[main]]
  id = "clases"
  parent = "servicios"
  name = "Clases"
  url = "/posts/clases"
  # pre = '<i class="fab fa-fw fa-github"></i>'
[[main]]
  id = "paginas"
  parent = "servicios"
  name = "Páginas web"
  url = "/posts/paginas"
  # pre = '<i class="fab fa-fw fa-github"></i>'