[[main]]
  name = "Servicios"
  identifier = "servicios"
  # pre = '<i class="fas fa-fw fa-chevron-circle-down"></i>'
[[main]]
  id = "clases"
  parent = "servicios"
  name = "Clases"
  url = "/about/clases"
  # pre = '<i class="fab fa-fw fa-github"></i>'
[[main]]
  id = "soporte"
  parent = "servicios"
  name = "Soporte"
  url = "/about/soporte"
  # pre = '<i class="fab fa-fw fa-github"></i>'